### ISSUE TITLE
[Java Generator] Generate interface instead of abstract class for Java

### ISSUE THREAD

**Issue by paulocoutinhox** [Snapchat/djinni#100]
Generate interface instead of abstract class for Java

This is a featured, but not an emergency. I will put it here only to we know that it can be done and how.

Source:
https://github.com/Asmot/djinni-rn/commit/84ebea92aa0fed8a2d28c4c7305463c17a7a9128

**Comment by neotron** [comment]
This is a blocker for us to move to this version of djinni for our project. We rely on interfaces on the java side of things. Seems like this fork happened before this feature was added to the dropbox repository.

**Comment by paulocoutinhox** [comment]
Is this feature interesting to you?

**Comment by neotron** [comment]
It is, since our project as generated by dropbox djinni depends on java using interfaces.

**Comment by paulocoutinhox** [comment]
I made the changes. Only have problems with testing now before make a PR.

**Comment by paulocoutinhox** [comment]
@neotron here is the PR: https://github.com/Snapchat/djinni/pull/105

**Comment by neotron** [comment]
Quick test shows that it works as expected. Only thing of note is that `public abstract` in the interface is redundant (it compiles but does nothing).

**Comment by paulocoutinhox** [comment]
@neotron done
