### ISSUE TITLE
What is considered experimental about future<>?

### ISSUE THREAD

**Issue by nolanw** [Snapchat/djinni#108]
Hello! Thank you for picking up Djinni maintenance, I'm excited to move off our local fork of the old Dropbox code.

I'm particularly excited about async interfaces. Can you say any more about why support is considered experimental? Are there planned changes (beyond what's in open issues)? Are you currently using it in production? How's that going? Can I help?

As much as you can say in public, of course. I'm happy to chat somewhere quieter if preferred. Thanks!

**Comment by paulocoutinhox** [comment]
There is nothing wrong with async features, it is working fine.

About chat, you can use Slack "mobilecpp.slack.com" channel djinni and djnni-development.

**Comment by LiFengSC** [comment]
We do use it in production code.  There is no known issue other than the lack of void future in the IDL.

**Comment by nolanw** [comment]
Awesome, thank you both! I'll head to the Slack with any further questions :)

**Comment by LiFengSC** [comment]
@nolanw the slack channel is run by a different group of developers who maintains another fork of the original djinni (https://github.com/cross-language-cpp/djinni-generator).  If you have questions about features specific to our version, you should either ask here, or DM me on slack (I'm a member of that slack channel).
