### ISSUE TITLE
32 bit flag to enum generation issue

### ISSUE THREAD

**Issue by martin00001313** [Snapchat/djinni#112]
In case of defining flags which later are translated to 32 bit unsigned enum, for the 32th enum value issue is occurred as '1<<31' is considered signed i32 operation and is overflow.
Instead, by generating with unsigned postfix 'u', i.e. '1u<<31' will work fine.

Proposal, use '1u<<shift' instead of '1 << shift'. Both C++ and ObjC support it fine

similar: https://github.com/cross-language-cpp/djinni-generator/issues/142

**Comment by paulocoutinhox** [comment]
Closed by https://github.com/Snapchat/djinni/pull/114
