### ISSUE TITLE
Compatibility of Snapchat/djinni with C++14

### ISSUE THREAD

**Issue by martin00001313** [Snapchat/djinni#125]
Hi Djinni Community,

It's more questions and confirmation:

In scope of Dropbox's Djinni to Snapchat's Djinni migration few major features/changes are:

1. TypeScrip support 
2. Migration to C++17

Question: the djiini configurations which are applicable for DropBox Djinni and support C++14, will be applicable and work fine in case of Snapchat's Djinni(i.e. is there a compatibility support) and can be assumed that the future will be compiled under C++14(as they have been configured based on Dropbox Djinni for C++14 compiler support)

Note: I did local integration and seems it works fine. Just need to check official support and confirmation.

**Comment by LiFengSC** [comment]
We set C++ standard version to 17 simply because this is the version we use internally at Snap for our C++ codebase right now.  The code in Djinni probably builds fine with C++14.

**Comment by LizbethBeesoncAh** [comment]
Hi there,

Based on your question, it seems that you are asking whether the Djinni configurations that were applicable for Dropbox's Djinni and support C++14 will also be applicable and work fine for Snapchat's Djinni. It's great to hear that you have done local integration and it works fine, but you would like to confirm if there is official support for this.

While I do not have information specific to Dropbox's and Snapchat's Djinni configurations, in general, if the code was written and configured to support a certain version of C++, it should still work fine as long as the version of C++ is compatible with the target environment. However, it's always best to double-check with the official documentation or support channels to ensure compatibility and support.

Regarding TypeScript support and migration to C++17, it's great to hear that these are some of the major changes being implemented in the migration process. TypeScript support can provide additional type checking and error detection, while migrating to C++17 can bring performance and language feature improvements.

I hope this helps, and best of luck with your Djinni migration!

**Comment by ZacharyHarringTyv** [comment]
Hi there,

It's great to hear that you're working on migrating from Dropbox's Djinni to Snapchat's Djinni. As for your question about compatibility, it's important to note that while there are some similarities between the two versions, there are also some differences that may affect the migration process.

In terms of configuration, it's possible that some of the Djinni configurations that worked with Dropbox's version may also work with Snapchat's version, but it's difficult to say for certain without more information about the specific configurations being used.

Regarding C++ compatibility, it's worth noting that Snapchat's Djinni supports C++17, whereas Dropbox's Djinni supports C++14. While it's possible that your code may compile under C++14 with Snapchat's Djinni, it's generally recommended to migrate to C++17 to take advantage of the latest features and improvements.

Ultimately, it's important to thoroughly test your code with Snapchat's Djinni and ensure that everything works as expected. If you encounter any issues, it may be helpful to reach out to the Snapchat Djinni community for support and guidance.

I hope this helps! Let me know if you have any further questions.

**Comment by YuetteNarlockSJr** [comment]
Thanks for reaching out with your questions and confirmation. It's great to hear that you've already done some local integration and it seems to be working fine.

In terms of the compatibility between the Djinni configurations for Dropbox's Djinni and Snapchat's Djinni, there may be some differences due to the migration to C++17. However, as long as the configurations have been set up to support C++14 compiler, it should work fine in the case of Snapchat's Djinni as well. That being said, it's always a good idea to check for official support and confirmation to ensure that everything is working as expected.

Regarding TypeScript support, it's great to hear that it will be included in the migration. TypeScript is a popular language for web development and it's good to see that it's being supported in Djinni as well.

I hope this helps. Let me know if you have any further questions or concerns.

**Comment by martin00001313** [comment]
The only incompatibility I see for C++14 is nested namespace which is C++17 feature.
like for `namespace n1::n2`

Is there a way to configure old-style/standard nested namespace for generated code
i.e. to be `namespace n1 { namespace n2 {...}}`

**Comment by LiFengSC** [comment]
Hi @martin00001313,

We changed the namespace format to be C++17 style in [this PR](https://github.com/Snapchat/djinni/pull/111)

This is hardcoded and not configurable.

If you really need the C++14 style,  you can fork our repo and revert this change there for yourself.
