### ISSUE TITLE
Plan to merge with cross-language-cpp djinni project?

### ISSUE THREAD

**Issue by paulo-coutinho** [Snapchat/djinni#30]
Hi,

There is any plan to put all modifications into "https://github.com/cross-language-cpp/djinni-generator"?

Thanks.

**Comment by finalpatch** [comment]
Hi @paulo-coutinho ,

There is no plan to merge with cross-language-cpp right now.  However, if you want to cherry pick some of our changes, please feel free to do so, as long as you credit them appropriately.

**Comment by delaitre-manfrotto** [comment]
@finalpatch : what about the other way around ? Do you guys plan on cherry-picking at least bug fixes from this other project? (e.g. https://github.com/cross-language-cpp/djinni-generator/commit/efabbc720591ba685e0c48c3333b31e575c7c923)

**Comment by finalpatch** [comment]
Hi @delaitre-manfrotto,  yes definitely.  I'll take a closer look at the PR you linked.

**Comment by finalpatch** [comment]
@delaitre-manfrotto  I made a slightly different fix based on your one
https://github.com/Snapchat/djinni/pull/33

**Comment by paulo-coutinho** [comment]
Somethings is nice and i use a lot, inclusive in my project ezored (github.com/ezored/ezored) that is:

- Executable for posix/win in releases: https://github.com/cross-language-cpp/djinni-generator/releases/tag/v1.3.0
- A way to download compiled/script to use djinni without need compile manually will be nice for tooling, like mine
- ScalaFmt that i updated recently to format all the code

Somethings new that i don't use, but is nice and was implemented on Djinni:
- Python support
- C# support
- JSON field

Will be nice if we join efforts in only one project to make it grow with all the features together, because we cant use some features from one and some from other. Will be more productive if everyone works to djinni together in one repository and it grow without multiple forks.

But it is only my opinion.

**Comment by paulo-coutinho** [comment]
Ok, i will close it for now.
