### ISSUE TITLE
Create release session on github

### ISSUE THREAD

**Issue by paulo-coutinho** [Snapchat/djinni#34]
Hi,

Can you create release session on Github with pre-compiled binary to we don't need compile it manually?

It will help me too into my tool to only download the binary instead of compile everything.

I can help with a pr or something if you need.

My suggestion is make something like other djinni fork that is create a binary for posix and windows:
https://github.com/cross-language-cpp/djinni-generator/releases

Thanks.

**Comment by finalpatch** [comment]
Hi @paulo-coutinho ,

This is a great idea, and we have discussed about it internally, too.  If we are going to make binary release for the code generator then I think we need to package and release versioned support library too, to match the code generator version, because the two usually have to work closely together.

At Snap we have never tested it on Windows as all our development work happen on posix systems. I'm not sure how much work is involved to get it back to work on Windows.

If you are willing to help creating the release workflow and/or bring back the Windows support,  we'll definitely appreciate that.

**Comment by paulo-coutinho** [comment]
Hi, I can make both. I'm on vacation now, but I will back soon and start both work, ok?

**Comment by finalpatch** [comment]
Thank you!  Feel free to work on your own pace. 

The way I imagine it is like this:

* We upload versioned djinni.jar binaries that can run anywhere with JRE installed
* We package and upload the support lib.  User should be able to download and unpack the files anywhere in their source tree and consume them there.
* There needs to be some way to ensure the code generator and support lib version 100% match

**Comment by paulo-coutinho** [comment]
Ok, nice.

- Versioned will be done by tag? Tags will have pattern "vMAJOR.MINOR.PATCH" with semantic version?
- A simple zip/tar for support-lib is necessary, correct?
- It always match since everything will be compiled and upload together.

**Comment by paulo-coutinho** [comment]
It is OK to exists now?

**Comment by finalpatch** [comment]
Do you mean making a release now?

**Comment by paulo-coutinho** [comment]
Are you going to create a new release now or are you still going to develop something?

**Comment by finalpatch** [comment]
No, it's good.  I'll make one.  Not sure what version number to use.  I personally don't think this repo has reached 1.0 quality so probably v0.5.0?  What do you think @bholmes-sc ?

**Comment by paulo-coutinho** [comment]
Maybe version `v0.0.1`.
What need to version be with more quality in your opinion?

**Comment by finalpatch** [comment]
I tried and got an error
```
Invalid workflow file : .github/workflows/release.yaml#L69
The workflow is not valid. .github/workflows/release.yaml (Line: 69, Col: 13): The identifier 'upload-release-asset-windows' may not be used more than once within the same scope.
```

**Comment by paulo-coutinho** [comment]
Fixed in my PR:
https://github.com/Snapchat/djinni/pull/49

**Comment by finalpatch** [comment]
I got another failure.  The action ran for 25minutes and got killed.
https://github.com/Snapchat/djinni/actions/runs/1676671698

**Comment by paulo-coutinho** [comment]
It was related with the code or with github?

![image](https://user-images.githubusercontent.com/395096/148861494-5ecbff5e-2be9-4578-a8d8-72e2762c8f75.png)

**Comment by paulo-coutinho** [comment]
@finalpatch try re-run, i don't have permission to do.

**Comment by finalpatch** [comment]
Tried, it seems stuck again.

**Comment by paulo-coutinho** [comment]
It works man:
https://github.com/Snapchat/djinni/runs/4770791094?check_suite_focus=true

**Comment by paulo-coutinho** [comment]
If it not uploaded to release, can be because of that bug. You will need delete the tag and create/release it again.

**Comment by finalpatch** [comment]
Yeah you are right, last run succeeded. Thanks!
