### ISSUE TITLE
Could cpp-djinni support macros defination anywhere ?

### ISSUE THREAD

**Issue by hyh712901** [Snapchat/djinni#50]
like below

```cpp
#if defined(DEBUG)
// some debug code
#endif
```

**Comment by finalpatch** [comment]
How would this work in other languages that don't have `#if`?  Everything defined in Djinni has to be translated to other langauges too, so if you have a field/method that is only available in C++'s debug or release mode, how would this translate to Java which does not have this separation?

**Comment by paulo-coutinho** [comment]
Hi @hyh712901,

If you want only debug macro, you can create an interface with `+c` only and a method called `is_debug():bool` with the implementation:

```
bool MyClass::isDebug()
{
    #if defined(DEBUG)
        return true;
    #endif

return false;
```

Maybe it help you.
