### ISSUE TITLE
Wasm/TS: Nullability is not enforced across the interface

### ISSUE THREAD

**Issue by bkotsopoulossc** [Snapchat/djinni#67]
When passing interfaces as function parameters, the generated typescript assumes every interface is *not nullable*, but the generated C++ code passes `std::sharedPtr<T>` types for each interface, which are *inherently nullable*. The typescript then has no way to legally check if the parameter is null or not (or undefined).

Let's say we have a djinni interface like this:
```
interface Foo +c {
  // ...
}

interface Bar +w {
  doSomething(foo: Foo);
}
```

On the C++ side, you call the web function and pass in an implementation of the C++ interface:
```
// .cpp
barObject->doSomething(std::make_shared<FooImpl>(...));
```

But it's also perfectly legal to pass in a nullptr:
```
// .cpp
barObject->doSomething(nullptr);
```

On the Typescript side, you may have some code like this to be defensive and check for the null pointer at runtime:
```
// .ts
const bar: Bar = {
  doSomething: (foo: Foo) => {
    if (!foo) { // this line fails type checking
      throw new Error()
    }
  }
}
```

But the if check fails type checking / linting because as far as typescript is concerned, that parameter can not be null/undefined, and the if check is always true.

We should either admit that interface types passed from c++ -> JS can be null, and codify that into the typescript signatures by generating them like `doSomething: (foo: (Foo | null)) => void`. Or, come up with some way to prevent null `shared_ptr` from crossing the boundary. This could be a runtime check, or it could be using a different type type that prevents construction from null ([example](https://github.com/microsoft/GSL/blob/main/include/gsl/pointers#L84)).

CC @LiFengSC

**Comment by finalpatch** [comment]
You are right. Interfaces should be nullable and this is how it works in Java and ObjC too. Unless you specified `--cpp-nn-type` to prevent `nullptr` from entering the C++ pointer.

**Comment by bholmes-sc** [comment]
My proposal here would be to first implement a runtime check for this anytime we make a call from C++ to TS.  
Don't we have some sort of proxy on the TS side that can verify if params are non-null?

**Comment by paulocoutinhox** [comment]
It was merged and solved. Can be closed, no? Thanks.
