### ISSUE TITLE
WASM: Handling exceptions in JS

### ISSUE THREAD

**Issue by bkotsopoulossc** [Snapchat/djinni#71]
**Background**

Emscripten as a framework supports [two ways](https://emscripten.org/docs/porting/exceptions.html) to build / run code that uses c++ exceptions. 

One is called "emscripten exception-handling" / emscripten-eh. In this method, C++ exceptions thrown actually bridge out to JS, and use JS to unwind the stack. The thing that ends up getting thrown is a JS number, which corresponds to the memory address of the exception_ptr on the wasm heap. The emscripten-generated JS code proxies each c++ method call and has special logic for handling catching errors of type `number`.

The other is called "wasm exception-handling" / wasm-eh. This is a new wasm proposal, where the runtime gets support to do its own stack unwinding, without relying on JS. In this implementation, you can throw and catch directly in wasm without bridging out to JS. When a C++ exception bubbles out of wasm and back to JS, the exception type is still a number, and it still corresponds to the memory address of the exception on the wasm heap. This new proposal is only supported in [recent browser versions](https://webassembly.org/roadmap/).

Since both of these implementations send a pointer back out to JS, the [recommendation](https://emscripten.org/docs/porting/Debugging.html#handling-c-exceptions-from-javascript) from emscripten to handle these errors is to expose a wasm function where you can take the `number`, cast it back to a pointer, access the exception object, and return the message back out to JS as a string. 

This works, but it means you need special logic in every JS catch block that is reachable from a c++ exception bubbling out. it's difficult to make sure this logic exists everywhere it is needed, and without it, debugging a caught exception is impossible, as the raw number has no useful information as it is. And, web apps sometimes rely on global uncaught error handlers to log and report errors that bubble all the way up to the root level (this could be the window, or it could be the root of a call stack from something like `setTimeout`).

**Change**

Djinni already has a proxy layer for JS calls to interfaces implemented in C++. It doesn't have a proxy layer for static methods, but this could be added.

This proxy layer could be used as a spot to catch C++ exceptions before they bubble out to JS, and transform them into canonical JS errors. 

We know that when an exception is thrown, it may bubble up a mixed call stack. For example, it may unwind through JS code, then back through C++ code, then back through JS code, etc. As noted in a [previous investigation](https://github.com/Snapchat/djinni/pull/35#issuecomment-996373986), JS errors don't bubble up correctly through C++ stack frames (at least for emscripten-eh). To solve this, the djinni proxy layer currently [converts](https://github.com/Snapchat/djinni/blob/master/support-lib/wasm/djinni_wasm.cpp#L61) from JS error to C++ exception when unwinding through a C++ frame.

So, the main change should be around converting C++ errors back to JS when unwinding through a JS frame.

CC @finalpatch @LiFengSC

**Comment by finalpatch** [comment]
Yes this can be done.  At some stage I actually had an implementation that handles non-static exceptions in this way.  I dropped that idea and switched back to throwing numbers because of the concern of increase in generated code size.  But since we tend not to use many static methods in djinni, this is probably not a big problem.

**Comment by finalpatch** [comment]
I'll give this another go.  It will certainly make the JS side error handling code a lot nicer.

**Comment by paulocoutinhox** [comment]
It was solved and can be closed, no? Thanks.
