### ISSUE TITLE
std::future to djinni::Future

### ISSUE THREAD

**Issue by sanjayrd** [Snapchat/djinni#76]
Native C++ concurrent libraries often result in std::futures being returned. However, there's no way to convert this to a Djinni Future when implementing a Djinni interface that returns a Djinni future. We might consider creating a wrapper or utility that helps with this conversion, or even implementing the Djinni future such that it inherits from std::future.

**Comment by LiFengSC** [comment]
I don't think this is possible until the `then()` method in the concurrency TS is implemented in std::future.  I had to create a new class specifically because of the lack of `then()`.
