### ISSUE TITLE
wasm: `CppProxyCacheEntry.count` required?

### ISSUE THREAD

**Issue by derolf** [Snapchat/djinni#90]
Hey,

I am wrapping my head whether the mechanics around `CppProxyCacheEntry.count` are ready required.

So, for referential integrity (and reuse), we have `cppProxyCache` that caches the JS-side proxy of the CPP-object.

Is `CppProxyCacheEntry.count` used for the sole purpose of shielding against a race condition between finalising the JS-side proxy -- WeakRef is dead, but not yet removed from cache -- and getting a proxy for the very same CPP-object?

Wouldn't it be enough to check during removal if the JS-side proxy is still the one stored in the cache?

**Comment by LiFengSC** [comment]
Hi Daniel,  the reason for adding this count can be found here https://github.com/Snapchat/djinni/pull/41

There are probably other ways to solve this problem, but it was the solution that I came up with at that point.

"Wouldn't it be enough to check during removal if the JS-side proxy is still the one stored in the cache?"  I'm not entirely sure what do you mean.  the JS-side proxy is already gone,  we don't have it any more, when we reach the finalizer.  (note that the `nativeRef` is not the same as the JS-side proxy object.
